import type { ReactNode } from "react";
import type { Metadata } from "next";
import { dir } from "i18next";

import { languages } from "../i18n/settings";
import { Footer } from "./_components/Footer";

import "./globals.css";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  readonly params: {
    readonly lng: string;
  };
  readonly children: ReactNode;
};

export default function RootLayout({ params: { lng }, children }: Props) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body>
        <main>{children}</main>
        <Footer lng={lng} />
      </body>
    </html>
  );
}
